In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/logistic-regression-heart-disease-prediction/framingham_heart_disease.csv


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('../input/logistic-regression-heart-disease-prediction/framingham_heart_disease.csv') #adding data
#print 1st 5 rows
dataset.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [3]:
dataset.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [4]:
dataset.dtypes

male                 int64
age                  int64
education          float64
currentSmoker        int64
cigsPerDay         float64
BPMeds             float64
prevalentStroke      int64
prevalentHyp         int64
diabetes             int64
totChol            float64
sysBP              float64
diaBP              float64
BMI                float64
heartRate          float64
glucose            float64
TenYearCHD           int64
dtype: object

In [5]:
data = dataset.drop(['education','BPMeds','totChol','BMI','glucose','heartRate' ], axis = 'columns')
data.head()

male  age  currentSmoker  cigsPerDay  prevalentStroke  prevalentHyp  \
0     1   39              0         0.0                0             0   
1     0   46              0         0.0                0             0   
2     1   48              1        20.0                0             0   
3     0   61              1        30.0                0             1   
4     0   46              1        23.0                0             0   

   diabetes  sysBP  diaBP  TenYearCHD  
0         0  106.0   70.0           0  
1         0  121.0   81.0           0  
2         0  127.5   80.0           0  
3         0  150.0   95.0           1  
4         0  130.0   84.0           0

In [6]:
cigarettes = data['cigsPerDay']
cigarettes.head()
#cig = cigs.mean()

0     0.0
1     0.0
2    20.0
3    30.0
4    23.0
Name: cigsPerDay, dtype: float64

In [7]:
cig = cigarettes.mean()

In [8]:
import math
integer_value = math.floor(cig)
integer_value

9

In [9]:
cigarettes.fillna(integer_value, inplace = True)
#hr.fillna(integer_value, inplace = True)
data.isnull().sum()

male               0
age                0
currentSmoker      0
cigsPerDay         0
prevalentStroke    0
prevalentHyp       0
diabetes           0
sysBP              0
diaBP              0
TenYearCHD         0
dtype: int64

In [10]:
#this data is labeled data
#independent variable (X) will be Age, Estimated Salary
#dependent variable(y) will be Purcahsed (It will be lable)

#define X,y
X = dataset.iloc[:, [ 1, 3]].values
y = dataset.iloc[:, 15].values

#print X,y
print(X[:5, :])
print(y[:5])

[[39  0]
 [46  0]
 [48  1]
 [61  1]
 [46  1]]
[0 0 0 1 0]


In [11]:
#import train_test_split from sklearn to train and test our data
from sklearn.model_selection import train_test_split 
#define 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

#print
print(X_train[:5],'\n', '\n', y_train[:5],'\n','\n', X_test[:5],'\n','\n', y_test[:5])

[[60  0]
 [42  1]
 [60  1]
 [67  0]
 [51  0]] 
 
 [0 0 1 1 0] 
 
 [[47  0]
 [58  0]
 [61  1]
 [45  0]
 [57  0]] 
 
 [0 0 0 0 0]


In [12]:
#dataset.info()
#check corelation among attributes of dataset 
dataset.corr()

male       age  education  currentSmoker  cigsPerDay  \
male             1.000000 -0.028979   0.017352       0.197596    0.317930   
age             -0.028979  1.000000  -0.165883      -0.213748   -0.192791   
education        0.017352 -0.165883   1.000000       0.018532    0.008085   
currentSmoker    0.197596 -0.213748   0.018532       1.000000    0.769690   
cigsPerDay       0.317930 -0.192791   0.008085       0.769690    1.000000   
BPMeds          -0.052506  0.122995  -0.010815      -0.048938   -0.046134   
prevalentStroke -0.004546  0.057655  -0.035112      -0.032988   -0.032707   
prevalentHyp     0.005313  0.307194  -0.081970      -0.103260   -0.066146   
diabetes         0.015708  0.101258  -0.038680      -0.044295   -0.037067   
totChol         -0.070322  0.262131  -0.023115      -0.046562   -0.026320   
sysBP           -0.035989  0.394302  -0.129631      -0.130230   -0.088780   
diaBP            0.057933  0.206104  -0.062316      -0.107746   -0.056632   
BMI              0.081672  0.135800  -0.137504      -0.167650   -0.092856   
heartRate       -0.116620 -0.012823  -0.054206       0.062356    0.075157   
glucose          0.006083  0.122256  -0.035721      -0.056826   -0.058960   
TenYearCHD       0.088428  0.225256  -0.054059       0.019456    0.057884   

                   BPMeds  prevalentStroke  prevalentHyp  diabetes   totChol  \
male            -0.052506        -0.004546      0.005313  0.015708 -0.070322   
age              0.122995         0.057655      0.307194  0.101258  0.262131   
education       -0.010815        -0.035112     -0.081970 -0.038680 -0.023115   
currentSmoker   -0.048938        -0.032988     -0.103260 -0.044295 -0.046562   
cigsPerDay      -0.046134        -0.032707     -0.066146 -0.037067 -0.026320   
BPMeds           1.000000         0.117365      0.261187  0.052047  0.080558   
prevalentStroke  0.117365         1.000000      0.074830  0.006949  0.000067   
prevalentHyp     0.261187         0.074830      1.000000  0.077808  0.163993   
diabetes         0.052047         0.006949      0.077808  1.000000  0.040278   
totChol          0.080558         0.000067      0.163993  0.040278  1.000000   
sysBP            0.254219         0.057009      0.696755  0.111283  0.208908   
diaBP            0.194227         0.045190      0.615751  0.050329  0.165182   
BMI              0.100668         0.025891      0.301318  0.087036  0.115767   
heartRate        0.015233        -0.017676      0.147261  0.048994  0.091125   
glucose          0.051176         0.018431      0.086834  0.617627  0.046408   
TenYearCHD       0.087489         0.061810      0.177603  0.097317  0.082184   

                    sysBP     diaBP       BMI  heartRate   glucose  TenYearCHD  
male            -0.035989  0.057933  0.081672  -0.116620  0.006083    0.088428  
age              0.394302  0.206104  0.135800  -0.012823  0.122256    0.225256  
education       -0.129631 -0.062316 -0.137504  -0.054206 -0.035721   -0.054059  
currentSmoker   -0.130230 -0.107746 -0.167650   0.062356 -0.056826    0.019456  
cigsPerDay      -0.088780 -0.056632 -0.092856   0.075157 -0.058960    0.057884  
BPMeds           0.254219  0.194227  0.100668   0.015233  0.051176    0.087489  
prevalentStroke  0.057009  0.045190  0.025891  -0.017676  0.018431    0.061810  
prevalentHyp     0.696755  0.615751  0.301318   0.147261  0.086834    0.177603  
diabetes         0.111283  0.050329  0.087036   0.048994  0.617627    0.097317  
totChol          0.208908  0.165182  0.115767   0.091125  0.046408    0.082184  
sysBP            1.000000  0.784002  0.326981   0.182246  0.140621    0.216429  
diaBP            0.784002  1.000000  0.377588   0.181255  0.061231    0.145299  
BMI              0.326981  0.377588  1.000000   0.067678  0.087377    0.075192  
heartRate        0.182246  0.181255  0.067678   1.000000  0.094500    0.022913  
glucose          0.140621  0.061231  0.087377   0.094500  1.000000    0.125544  
TenYearCHD       0.216429  0.145299  0.075192   0.0229

In [13]:
#normalization and feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [14]:
print(X_train[:5], '\n','\n', X_test[:5])

[[ 1.21793504 -1.00694672]
 [-0.88304973  0.9931012 ]
 [ 1.21793504  0.9931012 ]
 [ 2.03498468 -1.00694672]
 [ 0.16744265 -1.00694672]] 
 
 [[-0.29944285 -1.00694672]
 [ 0.98449229 -1.00694672]
 [ 1.33465642  0.9931012 ]
 [-0.5328856  -1.00694672]
 [ 0.86777091 -1.00694672]]


In [15]:
#create object of LogisticRegression class to refer as classifier
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(X_test[:5], '\n', '\n', y_pred[:5])

[[-0.29944285 -1.00694672]
 [ 0.98449229 -1.00694672]
 [ 1.33465642  0.9931012 ]
 [-0.5328856  -1.00694672]
 [ 0.86777091 -1.00694672]] 
 
 [0 0 0 0 0]


In [16]:
print(y_pred[:12],'\n','\n',y_test[:12])

[0 0 0 0 0 0 0 0 0 0 0 0] 
 
 [0 0 0 0 0 0 0 0 0 0 0 1]


In [17]:
#probability is 11/12 i.e 91.66% so, good to go

#we'll use a Confusion Matrix to evaluate exactly how accurate our Logistic Regression model is,
#the more the matching values, more is the accuracy

from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[890   0]
 [170   0]]


In [18]:
X = data[['male','age','currentSmoker','cigsPerDay','prevalentStroke','prevalentHyp','diabetes','sysBP','diaBP']]
y =  data['TenYearCHD']
X

male  age  currentSmoker  cigsPerDay  prevalentStroke  prevalentHyp  \
0        1   39              0         0.0                0             0   
1        0   46              0         0.0                0             0   
2        1   48              1        20.0                0             0   
3        0   61              1        30.0                0             1   
4        0   46              1        23.0                0             0   
...    ...  ...            ...         ...              ...           ...   
4233     1   50              1         1.0                0             1   
4234     1   51              1        43.0                0             0   
4235     0   48              1        20.0                0             0   
4236     0   44              1        15.0                0             0   
4237     0   52              0         0.0                0             0   

      diabetes  sysBP  diaBP  
0            0  106.0   70.0  
1            0  121.0   81.0  
2            0  127.5   80.0  
3            0  150.0   95.0  
4            0  130.0   84.0  
...        ...    ...    ...  
4233         0  179.0   92.0  
4234         0  126.5   80.0  
4235         0  131.0   72.0  
4236         0  126.5   87.0  
4237         0  133.5   83.0  

[4238 rows x 9 columns]

In [19]:
y

0       0
1       0
2       0
3       1
4       0
       ..
4233    1
4234    0
4235    0
4236    0
4237    0
Name: TenYearCHD, Length: 4238, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, random_state = 99)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [21]:
model.fit(X_train, y_train)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [22]:
model.score(X_test,y_test)

0.8632075471698113